[images]
  remote_images = ["https://images.unsplash.com/*"]

[build]
  command = "bun run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "bun run dev"
  port = 3000
  targetPort = 3000
